import { createFileRoute } from "@tanstack/react-router";
import { ProjectCard } from "@/components/project-card";
import { SiteShell } from "@/components/site-shell";
import { projectsSorted } from "@/data/projects";
import { PERSON } from "@/data/site";

export const Route = createFileRoute("/work/")({
  component: WorkPage,
  head: () => ({ meta: [{ title: `Work — ${PERSON.name}` }] }),
});

function WorkPage() {
  const projects = projectsSorted();
  return (
    <SiteShell>
      <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24">
        <h1 className="text-4xl font-medium tracking-tight text-fg sm:text-6xl">Work</h1>
        <p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted">
          Client websites generated by Polymorph Technologies — researched, structured, and printed
          for businesses in the Gulf.
        </p>
        <div className="mt-14 grid gap-10 sm:grid-cols-2">
          {projects.map((p) => (
            <ProjectCard key={p.id} project={p} to="/work/$slug" />
          ))}
        </div>
      </div>
    </SiteShell>
  );
}
