import { createFileRoute } from "@tanstack/react-router";
import { ProjectCard } from "@/components/project-card";
import { SiteShell } from "@/components/site-shell";
import { projectsSorted } from "@/data/projects";
import { PERSON } from "@/data/site";

export const Route = createFileRoute("/work/")({
  component: WorkPage,
  head: () => ({ meta: [{ title: `Work — ${PERSON.name}` }] }),
});

function WorkPage() {
  const projects = projectsSorted();
  return (
    <SiteShell>
      <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <p className="text-xs uppercase tracking-[0.2em] text-accent">Work</p>
        <h1 className="mt-3 font-display text-4xl text-fg sm:text-6xl">Shipped under Polymorph.</h1>
        <p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted">
          Client websites generated by Polymorph Technologies — researched, structured, and printed
          for businesses in the Gulf. Pentagon Cyber supplies the secure-by-default constraints.
        </p>
        <div className="mt-12 grid gap-4 sm:grid-cols-2">
          {projects.map((p) => (
            <ProjectCard key={p.id} project={p} to="/work/$slug" />
          ))}
        </div>
      </div>
    </SiteShell>
  );
}
