/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as PathIndexRouteImport } from './routes/path/index'
import { Route as PathSlugRouteImport } from './routes/path/$slug'
import { Route as PolymorphIndexRouteImport } from './routes/polymorph/index'
import { Route as PolymorphAboutRouteImport } from './routes/polymorph/about'
import { Route as PolymorphContactRouteImport } from './routes/polymorph/contact'
import { Route as PolymorphProcessRouteImport } from './routes/polymorph/process'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as PolymorphWorkIndexRouteImport } from './routes/polymorph/work/index'
import { Route as PolymorphWorkSlugRouteImport } from './routes/polymorph/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PathIndexRoute = PathIndexRouteImport.update({
  id: '/path/',
  path: '/path/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathSlugRoute = PathSlugRouteImport.update({
  id: '/path/$slug',
  path: '/path/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphIndexRoute = PolymorphIndexRouteImport.update({
  id: '/polymorph/',
  path: '/polymorph/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphAboutRoute = PolymorphAboutRouteImport.update({
  id: '/polymorph/about',
  path: '/polymorph/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphContactRoute = PolymorphContactRouteImport.update({
  id: '/polymorph/contact',
  path: '/polymorph/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphProcessRoute = PolymorphProcessRouteImport.update({
  id: '/polymorph/process',
  path: '/polymorph/process',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphWorkIndexRoute = PolymorphWorkIndexRouteImport.update({
  id: '/polymorph/work/',
  path: '/polymorph/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphWorkSlugRoute = PolymorphWorkSlugRouteImport.update({
  id: '/polymorph/work/$slug',
  path: '/polymorph/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/research': typeof ResearchRoute
  '/news/$slug': typeof NewsSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/polymorph/about': typeof PolymorphAboutRoute
  '/polymorph/contact': typeof PolymorphContactRoute
  '/polymorph/process': typeof PolymorphProcessRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/news/': typeof NewsIndexRoute
  '/path/': typeof PathIndexRoute
  '/polymorph/': typeof PolymorphIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/polymorph/work/$slug': typeof PolymorphWorkSlugRoute
  '/polymorph/work/': typeof PolymorphWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/research': typeof ResearchRoute
  '/news/$slug': typeof NewsSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/polymorph/about': typeof PolymorphAboutRoute
  '/polymorph/contact': typeof PolymorphContactRoute
  '/polymorph/process': typeof PolymorphProcessRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/news': typeof NewsIndexRoute
  '/path': typeof PathIndexRoute
  '/polymorph': typeof PolymorphIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/work': typeof WorkIndexRoute
  '/polymorph/work/$slug': typeof PolymorphWorkSlugRoute
  '/polymorph/work': typeof PolymorphWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/research': typeof ResearchRoute
  '/news/$slug': typeof NewsSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/polymorph/about': typeof PolymorphAboutRoute
  '/polymorph/contact': typeof PolymorphContactRoute
  '/polymorph/process': typeof PolymorphProcessRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/news/': typeof NewsIndexRoute
  '/path/': typeof PathIndexRoute
  '/polymorph/': typeof PolymorphIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/polymorph/work/$slug': typeof PolymorphWorkSlugRoute
  '/polymorph/work/': typeof PolymorphWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/research'
    | '/news/$slug'
    | '/path/$slug'
    | '/polymorph/about'
    | '/polymorph/contact'
    | '/polymorph/process'
    | '/skills/$slug'
    | '/work/$slug'
    | '/news/'
    | '/path/'
    | '/polymorph/'
    | '/skills/'
    | '/work/'
    | '/polymorph/work/$slug'
    | '/polymorph/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/research'
    | '/news/$slug'
    | '/path/$slug'
    | '/polymorph/about'
    | '/polymorph/contact'
    | '/polymorph/process'
    | '/skills/$slug'
    | '/work/$slug'
    | '/news'
    | '/path'
    | '/polymorph'
    | '/skills'
    | '/work'
    | '/polymorph/work/$slug'
    | '/polymorph/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/research'
    | '/news/$slug'
    | '/path/$slug'
    | '/polymorph/about'
    | '/polymorph/contact'
    | '/polymorph/process'
    | '/skills/$slug'
    | '/work/$slug'
    | '/news/'
    | '/path/'
    | '/polymorph/'
    | '/skills/'
    | '/work/'
    | '/polymorph/work/$slug'
    | '/polymorph/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  ResearchRoute: typeof ResearchRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PathSlugRoute: typeof PathSlugRoute
  PolymorphAboutRoute: typeof PolymorphAboutRoute
  PolymorphContactRoute: typeof PolymorphContactRoute
  PolymorphProcessRoute: typeof PolymorphProcessRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PathIndexRoute: typeof PathIndexRoute
  PolymorphIndexRoute: typeof PolymorphIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  PolymorphWorkSlugRoute: typeof PolymorphWorkSlugRoute
  PolymorphWorkIndexRoute: typeof PolymorphWorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/': {
      id: '/path/'
      path: '/path'
      fullPath: '/path/'
      preLoaderRoute: typeof PathIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$slug': {
      id: '/path/$slug'
      path: '/path/$slug'
      fullPath: '/path/$slug'
      preLoaderRoute: typeof PathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/': {
      id: '/polymorph/'
      path: '/polymorph'
      fullPath: '/polymorph/'
      preLoaderRoute: typeof PolymorphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/about': {
      id: '/polymorph/about'
      path: '/polymorph/about'
      fullPath: '/polymorph/about'
      preLoaderRoute: typeof PolymorphAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/contact': {
      id: '/polymorph/contact'
      path: '/polymorph/contact'
      fullPath: '/polymorph/contact'
      preLoaderRoute: typeof PolymorphContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/process': {
      id: '/polymorph/process'
      path: '/polymorph/process'
      fullPath: '/polymorph/process'
      preLoaderRoute: typeof PolymorphProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/work/': {
      id: '/polymorph/work/'
      path: '/polymorph/work'
      fullPath: '/polymorph/work/'
      preLoaderRoute: typeof PolymorphWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorph/work/$slug': {
      id: '/polymorph/work/$slug'
      path: '/polymorph/work/$slug'
      fullPath: '/polymorph/work/$slug'
      preLoaderRoute: typeof PolymorphWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  ResearchRoute: ResearchRoute,
  NewsSlugRoute: NewsSlugRoute,
  PathSlugRoute: PathSlugRoute,
  PolymorphAboutRoute: PolymorphAboutRoute,
  PolymorphContactRoute: PolymorphContactRoute,
  PolymorphProcessRoute: PolymorphProcessRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  PathIndexRoute: PathIndexRoute,
  PolymorphIndexRoute: PolymorphIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  PolymorphWorkSlugRoute: PolymorphWorkSlugRoute,
  PolymorphWorkIndexRoute: PolymorphWorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
